### PR TITLE
Fix root domain name parsing

### PR DESCRIPTION
**Pull request by silverwind**
This fixes a query for the root zone (issued from [`native-dns`](https://github.com/tjfontaine/node-dns)), like this:

``` js
var question = dns.Question({
    name: "",
    type: "NS",
});
```

Previously, the returning packet to this query could not be parsed and `native-dns` never received the packet and ran into a timeout.

From [RFC 1035](https://www.ietf.org/rfc/rfc1035.txt): The root domain name is defined by a single octet of zeros at 92; the root domain name has no labels.

### CODE REVIEW

**Comment by silverwind** [comment]
One part I wasn't totally sure was if the buffer cursor should be seeked forward by one byte before running `buff.tell()` to return the current location. The results seem fine with my current method though.

@tjfontaine any thought on this part?

**Comment by sindresorhus** [comment]
:+1: You should probably add a test ;)

**Comment by silverwind** [comment]
I'll look into adding a test.

**Comment by taoeffect** [comment]
@silverwind #7 was just merged. Could you check to see if this is relevant to that? (I'm focusing on releasing update to native-dns based on #7, which included many changes/fixes). If it is, can you submit the PR on top of most recent master?

**Comment by silverwind** [comment]
@taoeffect I think it should still apply, I'll rebase my branch shortly and test if everything is working fine.

Regarding the tests: I think there were 2 tests failing in the current build, and from a first glance, I think I need to tinker with the testing methods for it to test a `""` lookup correctly. Will let you know how that turns out.

**Comment by taoeffect** [comment]
Thanks @silverwind! Feel free to add your name to `package.json` in the list of authors! :)

**Comment by silverwind** [comment]
Will do, will probably check this out tomorrow.

**Comment by silverwind** [comment]
Looks like this PR is obsolete with your change in #7 which added `end = buff.tell();`. Queries for empty strings now work as expected. Great work!

**Comment by taoeffect** [comment]
Awesome (thx)!

**Pull request closed without merging**
